version: "2.3"
services:
  app:
    build: .
    shm_size: '16gb'
    volumes:
      - ./:/www/app/
    container_name: youtube-get-videoinfo-tool
    working_dir: /www/app/
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "8501:8501"
    tty: true
    restart: always